### ISSUE TITLE
missing assignment 3

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-syllabus-S19#2]

**Comment by shiffman** [comment]
A draft is posted but I may add / re-organize with some other ideas so leaving open.

**Comment by shiffman** [comment]
added some more links and ideas to the assignment page.

**Comment by kcconch** [comment]
link for assignment 3 is broken right now! should be https://github.com/nature-of-code/noc-syllabus-S19/wiki/Assignment-3

**Comment by shiffman** [comment]
Thanks, fixed now with 70b83954bf2e973b88aec7cc339b6e5fcfcdda6f!
